### DISCUSSION TITLE
ESP freezes occasionally - possible remote restart addition?

### DISCUSSION THREAD

**Discussion by daman7cz** [Yogui79/IntexPureSpa#60] [Q&A]
Hello Yogui79,
I am very grateful for your project and I use it daily. Platform ESP32, whirlpool 28462. Thank you for your great work.

I have observed that time to time the communication between whirlpool and ESP freezes. Signals sent through home assistant don't make any response by spa. Thermometer shows 162 deg C (see the screenshot). All I can do is to go and manually reboot (switch off and on power supply). After restart it works again like a charm.

I don't know if I am the only to have such issue or there is some pitfall in the code itself. Maybe something linked to ESP32 or something linked to 28462.

Temporarily I have solved it by inserting Sonoff S26 remotely switchable power socket. But in any case it would be great addon to be able to have function to remotely restart the ESP/Arduino.

![Screenshot_20220821-155044](https://user-images.githubusercontent.com/84605450/185914474-d3804e02-a256-4690-a600-bcf67cfee3de.png)

![IMG_20220822_131301_3](https://user-images.githubusercontent.com/84605450/185914391-0070092b-8f8b-4156-9700-870c6aa95343.jpg)

**Comment by guevara777** [comment]
I have the same issue, but very rare. It seems to depend on how stable your connection is. I put mine very near to the pool (have a garden shed right next to the pool). 

It also happens after restarting home assistant. 

I use 2 automations to solve this problems:
- 1 Automation that restarts the ESP on Home Asstiant Boot up
- 1 Automation that restarts the ESP when the connection gets lost (connection-with-pump switches to 0)

Hope that helps

Here is my mqtt.yaml configuration for the pool:
I have a "button"-entity for the restart and a binary_sensor for the communication with the pump.
I also bundled all entities to one device.

```
# Pool Heizungssteuerung
climate:
- unique_id: intex_pool_hvac
  name: "Intex Pool"

  # Gerät
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  
  modes: 
    - "heat"
    - "auto"
  current_temperature_topic: "IntexSpa/Actual Temperature"
  temperature_command_topic: "IntexSpa/Cmd Temperature Setpoint"
  temperature_state_topic: "IntexSpa/Temperature Setpoint"
  
  payload_on: "1"
  payload_off: "0"
  payload_available: "1"
  payload_not_available: "0"
  
  mode_command_topic: "IntexSpa/CMD HVAC Modeset"
  mode_state_topic: "IntexSpa/CMD HVAC Modeset"
  mode_state_template: >-
    {% set values = { '1':'auto', '2':'heat',  '3':'cool', '0':'off'} %}
    {{ values[value] if value in values.keys() else 'off' }}
  mode_command_template: >-
    {% set values = { 'auto':'4', 'heat':'5',  'cool':'3', 'off':'0'} %}
    {{ values[value] if value in values.keys() else '4' }}

  max_temp: "40"
  min_temp: "10"


# Intex Pool ESP-Restart Button
button:
- unique_id: intex_pool_restart
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  command_topic: IntexSpa/Cmd Reset ESP
  payload_press: "reset"
  name: "Intex Pool Restart"
  entity_category: "config"
  device_class: "restart"

# Intex Pool Decrease SetTemp Button
- unique_id: intex_pool_decrease
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  command_topic: IntexSpa/Cmd decrease
  payload_press: "1"
  name: "Intex Pool Set Temp Decrease"

# Intex Pool Increase SetTemp Button
- unique_id: intex_pool_increase
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  command_topic: IntexSpa/Cmd increase
  payload_press: "1"
  name: "Intex Pool Set Temp Increase"

# Intex Pool Filter Time Input Select
select:
- unique_id: intex_pool_filter_setup_time_select
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  command_topic: IntexSpa/Cmd water filter time
  #state_topic: IntexSpa/filter setup time
  name: "Intex Pool Filter Setup Time Select"
  options:
    - "0"
    - "2"
    - "4"
    - "6"

# MQTT Pool Schalter
switch:
- unique_id: intex_pool_power_switch
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  command_topic: IntexSpa/Cmd Power on off
  state_topic: IntexSpa/Power on
  payload_on: "1"
  payload_off: "0"
  name: "Intex Pool Power"
  
- unique_id: intex_pool_filter_switch
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  command_topic: IntexSpa/Cmd water filter on off
  state_topic: IntexSpa/filter on
  payload_on: "1"
  payload_off: "0"
  name: "Intex Pool Filter"
  
- unique_id: intex_pool_bubble_switch
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  command_topic: IntexSpa/Cmd bubble on off
  state_topic: IntexSpa/Bubble on
  payload_on: "1"
  payload_off: "0"
  name: "Intex Pool Bubble"
  
- unique_id: intex_pool_heater_switch
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  command_topic: IntexSpa/Cmd heater on off
  state_topic: IntexSpa/heater on
  payload_on: "1"
  payload_off: "0"
  name: "Intex Pool Heat"

# MQTT Pool Sensoren
sensor:
- unique_id: intex_pool_status
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  name: "Intex Pool Status"
  state_topic: "IntexSpa/Error Number"
  unit_of_measurement: 'E'
- unique_id: intex_pool_actual_temperature
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  name: "Intex Pool Actual Temperature"
  state_topic: "IntexSpa/Actual Temperature"
  unit_of_measurement: '°c'
- unique_id: intex_pool_set_temperature
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  name: "Intex Pool Set Temperature"
  state_topic: "IntexSpa/Temperature Setpoint"
  unit_of_measurement: '°c'
- unique_id: intex_pool_heater_status
  device:
    identifiers:
      - "Intex Spa"
    manufacturer: "Intex"
    model: "SPA"
    name: "Intex Spa Pool"
  name: "Intex Pool Heater Status"
  state_topic: "IntexSpa/heater state"
  value_template: >
    {% if value|float == 0 %}
      aus
    {% elif value|float == 1 %}
      standby
    {% elif value|float == 2 %}
      an
    {% endif %}

# Intex Pool Binärsensoren
binary_sensor:
  - unique_id: intex_pool_pumpenkommunikation
    device:
      identifiers:
        - "Intex Spa"
      manufacturer: "Intex"
      model: "SPA"
      name: "Intex Spa Pool"
    name: "Intex Pool Pumpenkommunikation"
    state_topic: "IntexSpa/Communication with pump"
    payload_on: "1"
    payload_off: "0"
    device_class: connectivity
```
