### DISCUSSION TITLE
HA automations

### DISCUSSION THREAD

**Discussion by rommess** [Yogui79/IntexPureSpa#68] [Show and tell]
G'day guys,
Like to share my 2 automations in HA: 1 for heating during night (electricity cheaper) and 1 creating chlorine during the day. 
Each automation trigger every 30 minutes to test time.
The best results are when the tablet is on the module (so not in sleeping mode)

heater:
```
alias: EXT Intex Spa chauffage
description: ""
trigger:
  - platform: time_pattern
    minutes: /30
condition: []
action:
  - if:
      - condition: time
        after: "01:59:00"
        before: "05:29:00"
    then:
      - if:
          - condition: state
            entity_id: switch.intex_pool_heat
            state: "off"
        then:
          - service: mqtt.publish
            data:
              topic: IntexSpa/Cmd Temperature Setpoint
              payload: "33"
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - type: turn_on
            device_id: a2096cd9aa657e9499091914b63290cf
            entity_id: switch.intex_pool_heat
            domain: switch
    else:
      - if:
          - condition: state
            entity_id: switch.intex_pool_heat
            state: "on"
        then:
          - type: turn_off
            device_id: a2096cd9aa657e9499091914b63290cf
            entity_id: switch.intex_pool_heat
            domain: switch
mode: single
```

sanitizer:
```
alias: EXT Intex Spa Sanitizer
description: ""
trigger:
  - platform: time_pattern
    minutes: /30
condition: []
action:
  - if:
      - condition: time
        after: "10:59:00"
        before: "15:59:00"
        enabled: true
    then:
      - if:
          - condition: state
            entity_id: switch.intex_pool_sanitizer
            state: "off"
        then:
          - device_id: a2096cd9aa657e9499091914b63290cf
            domain: select
            entity_id: select.intex_pool_sanitizer_setup_time_select
            type: select_option
            option: "8"
          - delay:
              hours: 0
              minutes: 0
              seconds: 11
              milliseconds: 0
          - type: turn_on
            device_id: a2096cd9aa657e9499091914b63290cf
            entity_id: switch.intex_pool_sanitizer
            domain: switch
    else:
      - if:
          - condition: state
            entity_id: switch.intex_pool_sanitizer
            state: "on"
        then:
          - type: turn_off
            device_id: a2096cd9aa657e9499091914b63290cf
            entity_id: switch.intex_pool_sanitizer
            domain: switch
mode: single
```
